os: linux
services:
   - docker
sudo: required
language: python
env:
  global:
    - CONAN_UPLOAD=1
    - CONAN_REFERENCE="nasl/0.4"
    - CONAN_USERNAME="jacmoe"
    - CONAN_REMOTE="dimi https://api.bintray.com/conan/dimi309/conan-packages"
    - CONAN_CHANNEL="stable"
    - CONAN_TOTAL_PAGES=1
    - CONAN_CURRENT_PAGE=1

matrix:
   include:
      - os: osx 
        osx_image: xcode8.3 # apple-clang 8.1
        language: generic
        env: CONAN_APPLE_CLANG_VERSIONS=8.1 # CONAN_CURRENT_PAGE=apple-clang_81   
      - os: osx 
        osx_image: xcode8.2  # apple-clang 8.0
        language: generic
        env: CONAN_APPLE_CLANG_VERSIONS=8.0 # CONAN_CURRENT_PAGE=apple-clang_80    

before_install:
 - chmod +x ./.travis/install.sh
 - chmod +x ./.travis/run.sh

install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh
